apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: myapp
spec:
  replicas: 5
  strategy:
    canary:
      steps:
        - setWeight: 10     # 10% to new version, 90% stays on old
        - pause: { duration: 60 }  # Wait 60s
        - setWeight: 50
        - pause: { duration: 60 }
        - setWeight: 100    # Full promotion
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: nginx:1.19  # New version here
          ports:
            - containerPort: 80
